apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/acme-challenge-type: http01
    certmanager.k8s.io/issuer: letsencrypt-prod
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
  name: ${project_name}
  namespace: ${namespace}
spec:
  rules:
  - host: ${domain}
    http:
      paths:
      - path: /
        backend:
          serviceName: ${project_name}
          servicePort: 80
  tls:
  - hosts:
    - ${domain}
    secretName: ${domain}-tls
